### ISSUE TITLE
Bounding box searching in Explore allows invalid geocoordinates 

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#162] opened 2015-06-05 21:27 UTC
Sorry to drop this on you guys but basically a bug that was not around pre-deployment, pre-integration as I know this was working at one point. It basically prevents a user from panning and seeing results and from sharing urls: (also same behaviour on stamen gtihub instance and prod)
Eg. scroll WEST and search bb on Philippines= invalid results
https://dev-holos.berkeley.edu/explore/#&q=&bbox=-259.365234375,-0.13183582116660822,-212.51953124999997,20.50935458871459&page_size=100

Scroll EAST and search bb on Philippines= ok
https://dev-holos.berkeley.edu/explore/#&q=&bbox=99.36035156249999,3.908098881894123,146.2060546875,24.246964554300924&page_size=100

pls. coordinate with @shoeswat who will help and deploy any fixes on the prod version on holos.berkeley.edu

**Comment by postfalk** [comment] 2015-06-05 21:33
Can you pls repost on bee so that Brian Galey can look at it? Thanks

On Fri, Jun 5, 2015 at 2:27 PM, Michelle Koo <notifications@github.com>
wrote:

> Sorry to drop this on you guys but basically a bug that was not around
> pre-deployment, pre-integration as I know this was working at one point. It
> basically prevents a user from panning and seeing results and from sharing
> urls: (also same behaviour on stamen gtihub instance and prod)
> Eg. scroll WEST and search bb on Philippines= invalid results
>
> https://dev-holos.berkeley.edu/explore/#&q=&bbox=-259.365234375,-0.13183582116660822,-212.51953124999997,20.50935458871459&page_size=100
>
> Scroll EAST and search bb on Philippines= ok
>
> https://dev-holos.berkeley.edu/explore/#&q=&bbox=99.36035156249999,3.908098881894123,146.2060546875,24.246964554300924&page_size=100
>
> pls. coordinate with @shoeswat <https://github.com/shoeswat> who will
> help and deploy any fixes on the prod version on holos.berkeley.edu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/162>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by mkoo** [comment] 2015-06-05 21:42
yep!
but this is shared through the instances so fixes anywhere should be shared.

**Comment by postfalk** [comment] 2015-06-05 21:47
I think the problem is actually specific to slippy map viewers and should indeed be fixed in the ecoengine app by Stamen. @shoeswat Just calculate the valid longitude value with the formel

valid_longitude = ((out_of_range_longitude+180) modulo 360) - 180 

prior the AJAX request and it should work

**Comment by danrademacher** [comment] 2015-06-05 22:59
So this is an issue around the dateline, right?

Looks like the search by bbox is determined here:
https://github.com/stamen/ecoengine/blob/master/viewJS/ecoengine-explore.js#L1015-L1022

**Comment by shoeswat** [comment] 2015-06-05 23:03
okay i'll play around with modulo-ing the params dan pointed out -- thanks!

**Comment by shoeswat** [comment] 2015-06-05 23:06
query() (L1021) submits the query to the API, the API is returning records
though properly (if you look at the bottom and sides, records are
populated), its just not displaying points on the map

how are the points being rendered on the map?

**Comment by shoeswat** [comment] 2015-06-05 23:21
oic is this addMarkers() (L500)?

**Comment by syntagmatic** [comment] 2015-06-09 00:23
@shoeswat , it looks like Markers don't automatically repeat themselves with tiled world copies without some configuration.

One option appears to be enabling `worldCopyJump`

http://stackoverflow.com/questions/28977891/leaflet-mapbox-markers-dont-repeat-after-scrolling-around-the-atlas

Another option could be disabling the tiled world copies by constraining panning to a single world with boundaries.

http://leafletjs.com/reference.html#tilelayer-nowrap

**Comment by shoeswat** [comment] 2015-06-10 21:22
@syntagmatic thanks!
I specified worldCopyJump in the L.map instance and it appears to have worked.

**Closed by shoeswat** 2015-06-10 21:22 UTC
Labels: bug

**Comment by syntagmatic** [comment] 2015-06-10 21:58
Tested out the Explore links you sent. It works. Nice work Yoshi!

**Comment by mkoo** [comment] 2015-06-11 06:31
So great to have this fixed! Now can search and map data globally again...
Please let me know when pushed to production.

Stamen: will you update your versions too since it is fundamental to using
the tools? (just curious for future reference)

**Comment by syntagmatic** [comment] 2015-06-18 20:19
@mkoo just pushed the fix!
